# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f0137846b4eb662cbb0090f7d1a76c24999f52b40dcdc0eac11c3d7c36d3c0dba27a95ba4a5e222efe32d569f81345e15ad497de3a632070e0eab023c5c310

test:
  secret_key_base: f126aa7f91e4d0243cfd51a9b1e5cfe1afb98737d13f91c6c74922dbe1d5cf2b6681e3413c46a5c4ac7c722476c7290782c6720b3e9b1f327e6756fa2ed7a546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
